export const personalData = [
    {
      name: "Jonathan Olbes",
      description: "trainee Full-stack developer whit 6 month of experience MERN stack",
      works: "Freelace on Freelancer.com and Upwork.com",
      image: "/profile.png",
      yearsexperience: "1",
      yearsold: "42",
    },
];

export const links = [
    {
        name: "Home",
        hash: "/",
    },
    {
        name: "Experience",
        hash: "#experience",
    },
    {
        name: "Skills",
        hash: "#skills",
    },
    {
        name: "Projects",
        hash: "#projects",
    },
    {
        name: "About",
        hash: "#about",
    },
    {
        name: "Contact",
        hash: "#contact",
    },
];

export const experienceData = [
    {
        id: 1,
        title: "Freelance Web Developer",
        company: "Freelance",
        location: "Worldwide",
        startDate: "2023",
        endDate: "Present",
        description: `"I have been working as a freelance web, developer for the past 4 mouth. I have worked with clients 
        from all over the world and have helped them build their websites and web applications."`,
        linkweb: "https://www.freelancer.com/u/olbesdev/",
    },
    {
        id: 2,
        title: "System Analyst Level 1",
        company: "Bodytech Colombia",
        location: "Bogotá, Colombia",
        startDate: "2022",
        endDate: "Present",
        description: `"Carry out IT support, monitoring and incident management work at the 83 headquarters nationwide. 
        Management of tickets and calls for technological and application incidents."`,
        linkweb: "https://bodytech.com.co/",
    },
    {
        id: 3,
        title: "System Analyst Level 1",
        company: "Scotiabank Colpatria",
        location: "Bogotá, Colombia",
        startDate: "2021",
        endDate: "2021",
        description: `Attention to computer incidents generated by ticket or calls.
        In-person and/or remote support for collaborating agents in the Colpatria tower and branches in Bogotá
        Installation, configuration and repairs of hardware and software. work at the 83 headquarters nationwide. 
        Management of tickets and calls for technological and application incidents."`,
        linkweb: "https://www.scotiabankcolpatria.com/",
    },
    {
        id: 4,
        title: "Resident Technical Support Analyst",
        company: "R & S Soluciones",
        location: "Bogoá, Colombia",
        startDate: "2016",
        endDate: "2017",
        description: `Attention to incidents on the platforms used by the, Trust Insurance company 
        through ticket, chat or, calls. Technical support in different applications, Windows, Office,
        365, Isosystem (Document management), creation of users and profile mapping in Active Directory, 
        Backup sequential, incremental and monthly, custody of backup's Iron Mountain, data center access custody.
        OSIRIS application (Core) installation and configuration, modification of passwords and access 
        profiles as well as the creation and deletion of access profiles. Solutions to printing errors 
        on the application.."`,
        linkweb: "https://rys.com.co/",
    },
    {
        id: 5,
        title: "Resident Technical Support Analyst",
        company: "Seguros Confianza S.A.",
        startDate: "2016",
        endDate: "2017",
        description: `Attention to incidents on the platforms used by the, Trust Insurance company 
        through ticket, chat or, calls. Technical support in different applications, Windows, Office,
        365, Isosystem (Document management), creation of users and profile mapping in Active Directory, 
        Backup sequential, incremental and monthly, custody of backup's Iron Mountain, data center access custody.
        OSIRIS application (Core) installation and configuration, modification of passwords and access 
        profiles as well as the creation and deletion of access profiles. Solutions to printing errors 
        on the application.."`,
        linkweb: "https://www.confianza.com.co/",
    },
];

export const projectData = [ 
    {
        site: "Hijueputa ¡Qué rico! - Ecommerce Website",
        title: "Workpress Developer",
        company: "Freelance",
        date: "2022 - 2022",
        description: `Build and maintain websites using WordPress. Customize existing themes and plugins. 
        Develop and maintain complex WordPress-based applications. Integrate WordPress with other third-party services.`,
        website: "https://hijueputaquerico.com",
        imgUrl: "",
        technologies: ["Wordpress", "Woocommerce", "PHP", "MySQL", "CSS", "HTML", "JavaScript", "Bootstrap", "Figma"]
    },
    {
        site: "Kitsune Sutoa - Ecommerce Website",
        title: "Workpress Developer",
        company: "Freelance",
        date: "2023 - 2023",
        description: `Build and maintain websites using WordPress. Customize existing themes and plugins. 
        Develop and maintain complex WordPress-based applications. Integrate WordPress with other third-party services.`,
        website: "https://kitsunesutoa.com",
        imgUrl: "",
        technologies: ["Wordpress", "Woocommerce", "PHP", "MySQL", "CSS", "HTML", "JavaScript", "Bootstrap", "Figma"]
    },
    {
        site: "OlbesDev - Portfolio Website",
        title: "NextJS Developer",
        company: "Freelance",
        date: "2024 - 2024",
        description: `Build and maintain website using NextJS. Hostage portfolio on Vercel.`,
        website: "https://olbesdev.xyz",
        imgUrl: "",
        technologies: ["HTML", "CSS", "JavaScript", "ReactJS", "NextJs", "Figma"]
    },
    
]

export const skillData = [ 
    {
        name: "HTML",
    },
    {
        name: "CSS",
    },
    {
        name: "JavaScript",
    },
    {
        name: "ReactJS",
    },
    {
        name: "NextJS",
    },
    {
        name: "TailwindCSS",
    },
    {
        name: "NodeJS",
    },
    {
        name: "ExpressJS",
    },
    {
        name: "MongoDB",
    },
    {
        name: "MySQL",
    },
    {
        name: "WordPress",
    },
    {
        name: "Figma",
    }
    
]

